export interface Video {
  id: string;
  title: string;
  categories: string[];
  tags: string[];
  src: string;
  thumb: string;
  duration: string;
  addedAt: string;
  model: string;
}

export const videos: Video[] = [
  {
    id: "V1",
    title: "F  me Until You Fill Me",
    categories: ["Fashion"],
    tags: ["#Fashion", "#Luxury", "#Travel"],
    src: "//mixdrop.top/e/ow98dk1gskvpgl",
    thumb: "https://i.ibb.co/nszKz1KC/Fk-Me-Until-You-Fill-Me.jpg",
    duration: "1680",
    addedAt: "2026-03-20T20:05:00Z",
    model: "Emiri Momota"
  },
  {
    id: "V2",
    title: "Sx Sells Eliza Ibarra & Mick Blue",
    categories: ["Fashion"],
    tags: ["#Fashion", "#Glamour", "#Premium"],
    src: "//mixdrop.top/e/4dmqowvzfq3j9x4",
    thumb: "https://i.ibb.co/tT9PLsYx/Sx-Sells-Eliza-Ibarra-Mick-Blue.webp",
    duration: "1920",
    addedAt: "2026-04-08T10:00:00Z",
    model: "Eliza Ibarra"
  },
  {
    id: "V3",
    title: "Jia Episode 1",
    categories: ["Lifestyle"],
    tags: ["#Lifestyle", "#Luxury", "#Trending"],
    src: "//mixdrop.top/e/l7qmv4rnsq1gr96",
    thumb: "https://i.ibb.co/27sWmgPF/vixen-jia-episode-1.webp",
    duration: "1000",
    addedAt: "2026-04-08T10:30:00Z",
    model: "Jia Lissa, Agatha Vega"
  },
  {
    id: "V4",
    title: "The Most Beautiful Red Head You Have Ever Seen",
    categories: ["Glamour"],
    tags: ["#Glamour", "#Style", "#Fashion"],
    src: "//mixdrop.top/e/gjkwm8ndfw4jmk8",
    thumb: "https://i.ibb.co/kspHwDbS/Vixen-the-Most-Beautiful-Red-Head-You-Have-Ever-Seen.webp",
    duration: "2000",
    addedAt: "2026-04-08T11:00:00Z",
    model: "Jia Lissa"
  },
  {
  id: "V5",
  title: "24 Hours",
  categories: ["Lifestyle"],
  tags: ["#Lifestyle", "#Trending", "#Luxury"],
  src: "//mxdrop.sx/e/l7nq9q09fl99lr",
  thumb: "https://i.ibb.co/jZgGLF47/24-Hours.webp",
  duration: "1200",
  addedAt: "2026-04-08T11:30:00Z",
  model: "Rae Lil Black"
},
{
  id: "V6",
  title: "24 Hours Part 2",
  categories: ["Lifestyle"],
  tags: ["#Lifestyle", "#Luxury", "#Trending"],
  src: "//mxdrop.sx/e/vk7zqzdrh1zno3",
  thumb: "https://i.ibb.co/C31CxZ8P/24-Hours-Part-2.webp",
  duration: "1200",
  addedAt: "2026-04-08T12:00:00Z",
  model: "Rae Lil Black"
},
{
  id: "V7",
  title: "24 Hours Part 3",
  categories: ["Lifestyle"],
  tags: ["#Lifestyle", "#Luxury", "#Trending"],
  src: "//mxdrop.sx/e/gj0kdkqwaed3g7",
  thumb: "https://i.ibb.co/C31CxZ8P/24-Hours-Part-2.webp",
  duration: "1200",
  addedAt: "2026-04-08T12:30:00Z",
  model: "Rae Lil Black"
},
{
  id: "V8",
  title: "Rae Lil Black Makes First Raw Scene",
  categories: ["Glamour"],
  tags: ["#Glamour", "#Premium", "#Trending"],
  src: "//mxdrop.sx/e/7k9pjpmet784q3",
  thumb: "https://i.ibb.co/7tmsVWbr/rae-lil-black-in-first-blacked-raw.webp",
  duration: "1920",
  addedAt: "2026-04-08T13:00:00Z",
  model: "Rae Lil Black"
},
{
  id: "V9",
  title: "Cok Crazy Rae Handles",
  categories: ["Glamour"],
  tags: ["#Glamour", "#Luxury", "#Premium"],
  src: "//mxdrop.sx/e/7k9pjples77nd6",
  thumb: "https://i.ibb.co/Kcf5HMYJ/Crazy-Rae-Handles-Two.webp",
  duration: "1920",
  addedAt: "2026-04-08T13:30:00Z",
  model: "Rae Lil Black"
},
{
  id: "V10",
  title: "Naughty Beauty Rae ",
  categories: ["Fashion"],
  tags: ["#Fashion", "#Glamour", "#Premium"],
  src: "//mxdrop.sx/e/9w1qxqews0j398",
  thumb: "https://i.ibb.co/jPHWzvTK/Naughty-Beauty-Rae-Sed-Man.webp",
  duration: "900",
  addedAt: "2026-04-08T14:00:00Z",
  model: "Rae Lil Black"
},
{
  id: "V11",
  title: "Perfect Babe Rae Cant Resist Jasons B",
  categories: ["Fashion"],
  tags: ["#Fashion", "#Luxury", "#Trending"],
  src: "//mxdrop.sx/e/dk3dr3nwf1em7v",
  thumb: "https://i.ibb.co/bM8nVmMD/Perfect-Rae-Cant.webp",
  duration: "1920",
  addedAt: "2026-04-08T14:30:00Z",
  model: "Rae Lil Black"
},
{
  id: "V12",
  title: "Wild Temptation",
  categories: ["Glamour"],
  tags: ["#Glamour", "#Style", "#Premium"],
  src: "//mxdrop.sx/e/gj0kd09pcjzkp8",
  thumb: "https://i.ibb.co/R4P3P4RG/Wild-Temptation.webp",
  duration: "1200",
  addedAt: "2026-04-08T15:00:00Z",
  model: "Rae Lil Black"
},
{
  id: "V13",
  title: "Lus At First Sight",
  categories: ["Glamour"],
  tags: ["#Glamour", "#Luxury", "#Trending"],
  src: "//mxdrop.sx/e/wlkmwnx7a0o3m9",
  thumb: "https://i.ibb.co/nMVqhGT8/Lu-At-First-Sight.webp",
  duration: "1200",
  addedAt: "2026-04-08T15:30:00Z",
  model: "Rae Lil Black"
},
{
  id: "V14",
  title: "Y2K photo shoot with a beauty.",
  categories: ["Glamour"],
  tags: ["#Glamour", "#Luxury", "#Trending"],
  src: "https://video.damplips.com/video7/714/63.mp4",
  thumb: "https://files.catbox.moe/x08jwt.jpg",
  duration: "600",
  addedAt: "2026-04-08T15:30:00Z",
  model: "Elly Clutch"
},
{
  id: "V15",
  title: "Green Eyed Monster",
  categories: ["Glamour"],
  tags: ["#Glamour", "#Luxury", "#Trending"],
  src: "https://mxdrop.sx/e/ow4w3gzoim8rzo",
  thumb: "https://i.ibb.co/Gf0WmpJX/Green-Eyed-Monster.webp",
  duration: "2700",
  addedAt: "2026-05-015T15:30:00Z",
  model: "Rae Lil Black"
},
{
  id: "V16",
  title: "Knockout Bab Fk Two Cops On Duty",
  categories: ["Glamour"],
  tags: ["#Glamour", "#Luxury", "#Trending"],
  src: "https://mxdrop.sx/e/mk14136ziklodw",
  thumb: "https://i.ibb.co/kgnG0PYw/blackedraw-knockout-fk-two-cops-on-duty-3840x2160.webp",
  duration: "3000",
  addedAt: "2026-05-018T15:30:00Z",
  model: "Agatha Vega, Ella Hughes"
},
{
  id: "V17",
  title: "VR yoga session ends with the Asian cutie being pummeled",
  categories: ["Glamour"],
  tags: ["#Glamour", "#Luxury", "#Trending"],
  src: "https://video.damplips.com/video7/632/19.mp4",
  thumb: "https://i.ibb.co/hRvcF6F7/VR-yoga-session-ends-with-the-Asian-cutie-being-pummeled.jpg",
  duration: "600",
  addedAt: "2026-05-018T15:30:00Z",
  model: "Emiri Momota"
},
{
  id: "V18",
  title: "Stun Asan bab gets lickd and pouned good in the bedroom",
  categories: ["Glamour"],
  tags: ["#Glamour", "#Luxury", "#Trending"],
  src: "https://video.damplips.com/video7/655/01.mp4",
  thumb: "https://i.ibb.co/G31D88wX/Stunning-Asian-and-pounded-good-in-the-bedroom.jpg",
  duration: "600",
  addedAt: "2026-05-018T15:30:00Z",
  model: "Emiri Momota"
},
{
  id: "V19",
  title: "Three girls were amazed when they heard about the owner of the biggest cck",
  categories: ["Glamour"],
  tags: ["#Glamour", "#Luxury", "#Trending"],
  src: "https://video.damplips.com/video7/655/01.mp4",
  thumb: "https://i.ibb.co/LdXYSRZd/three-girls.jpg",
  duration: "600",
  addedAt: "2026-05-019T15:30:00Z",
  model: "Kwini Kim"
},
{
  id: "V20",
  title: "Taking a morning bath with a cute aked girl",
  categories: ["Glamour"],
  tags: ["#Glamour", "#Luxury", "#Trending"],
  src: "https://video.damplips.com/video7/710/22.mp4",
  thumb: "https://i.ibb.co/d0sFkhng/bath-girl.jpg",
  duration: "600",
  addedAt: "2026-05-019T15:30:00Z",
  model: "Kwini Kim"
}  
];

export const categories = [
  { count: 1814, name: "Urban Chic" },
  { count: 832, name: "Wanderlust Wear" },
  { count: 117, name: "Eastern Glow" },
  { count: 1398, name: "Starlight Glam" },
  { count: 2173, name: "Timeless Silhouettes" },
  { count: 477, name: "Statement Style" },
  { count: 406, name: "Midnight Luxe" },
  { count: 172, name: "Campus Couture" },
  { count: 387, name: "Kinship Fashion" },
  { count: 490, name: "Squad Vibes" },
  { count: 436, name: "Effortless Chic" },
  { count: 165, name: "Glow Routines" },
  { count: 1252, name: "Couture Classics" },
  { count: 700, name: "Viral Trends" },
  { count: 554, name: "Opulent Looks" },
  { count: 75, name: "Fiesta Flair" },
  { count: 821, name: "Bonded Style" },
  { count: 262, name: "Family Glow" },
  { count: 1028, name: "Runway Icons" },
  { count: 430, name: "Pure Elegance" },
  { count: 733, name: "Modern Muse" },
  { count: 1283, name: "Signature Look" },
  { count: 644, name: "Gen Z Glam" },
  { count: 1700, name: "Crew Chic" },
  { count: 2411, name: "Fresh Wave" },
  { count: 624, name: "Radiant Aura" },
];

export const modelCodes = [
  "Abella Danger",
  "Adria Rae",
  "Agatha Vega",
  "Ailee Anne",
  "Alexia Anders",
  "Alexis Tae",
  "Amber Moore",
  "Ameena Green",
  "Angel Gostosa",
  "Angel Youngs",
  "Angelina Moon",
  "Angie Faith",
  "Anissa Kate",
  "Aria Lee",
  "Aria Taylor",
  "Armani Black",
  "Ashby Winter",
  "Ashley Aixi",
  "Ashley Alexander",
  "Avery Cristy",
  "Azul Hermosa",
  "Bailey Base",
  "Barbie Feels",
  "Blake Blossom",
  "Britney Dutch",
  "Brooklyn Gray",
  "Catherine Knight",
  "Cecelia Taylor",
  "Chanel Camryn",
  "Cherie DeVille",
  "Chloe Amour",
  "Chloe Surreal",
  "Christy White",
  "Coco Lovelock",
  "Codi Vore",
  "Dana Vespoli",
  "Dani Daniels",
  "Della Cate",
  "Demi Hawks",
  "Dolly Orchid",
  "Eliza Ibarra",
  "Ella Hughes",
  "Ellie Leen",
  "Ellie Nova",
  "Elly Clutch",
  "Elsa Jean",
  "Emily Willis",
  "Emiri Momota",
  "Emma Rosie",
  "Eva Elfie",
  "Eva Generosi",
  "Eve Sweet",
  "Freya Parker",
  "Gal Ritchie",
  "Gianna Dior",
  "Hailey Rose",
  "Hazel Heart",
  "Hazel Moore",
  "Isa Bella",
  "Janice Griffith",
  "Jasmine Sherni",
  "Jazmin Luv",
  "Jia Lissa",
  "Joanna Wei",
  "Julia James",
  "Katana Kombat",
  "Katie Kush",
  "Kayley Gunner",
  "Kelly Collins",
  "Kendra Spade",
  "Kimmy Kimm",
  "Kwini Kim",
  "Kylie Rocket",
  "Lana Rhoades",
  "Lana Smalls",
  "Leana Lovings",
  "Lexi Lore",
  "Lexi Luna",
  "Lexi Smith",
  "Lia Lin",
  "Lilly Bell",
  "Little Angel",
  "Little Caprice",
  "Liya Silver",
  "Liz Jordan",
  "Lucy Mochi",
  "Lulu Chu",
  "Matty Mila Perez",
  "Megan Longoria",
  "Megan Mistakes",
  "Melanie Marie",
  "Millie Morgan",
  "Molly Little",
  "Nikki Nicole",
  "Octavia Red",
  "Queenie Sateen",
  "Rae Lil Black",
  "Reina Ohara",
  "Rikako Katayama",
  "Riley Reid",
  "Rissa May",
  "Ryan Reid",
  "Scarlett Alexis",
  "Scarlett Jones",
  "Scarlit Scandal",
  "Shay Sights",
  "Shelena",
  "Sirena Milano",
  "Sonya Blaze",
  "Stefany Kyler",
  "Stella Luxx",
  "Sybil",
  "Tori Black",
  "Valentina Nappi",
  "Vanessa Alessia",
  "Vanna Bardot",
  "Venus Valencia",
  "Violet Gems",
  "Violet Myers",
  "XxLayna Marie",
  "Yhivi"
];

export const modelcodes = modelCodes;



export const filters = ["All", "Indian", "Foreign", "Trending", "Premium", "4K", "New", "Popular", "Models"];

export interface ModelProfile {
  image: string;       // main / fallback portrait
  card?: string;       // 9:16 grid poster (defaults to image)
  hero?: string;       // wide cinematic banner (defaults to image)
  portrait?: string;   // side portrait (defaults to image)
  bio: string;
}

export const modelProfiles: Record<string, ModelProfile> = {
  "Abella Danger": {
    "image": "https://i.ibb.co/DfRpszH6/Abella-Danger-2.png",
    "card": "https://i.ibb.co/DfRpszH6/Abella-Danger-2.png",
    "hero": "https://i.ibb.co/8D3108Th/tushy-abella-danger-3840x1600.webp",
    "portrait": "https://i.ibb.co/6cZXrVxQ/tushy-abella-danger-1900x1300.webp",
    "bio": "Abella Danger is known for bold glamour, cinematic beauty and a commanding editorial presence that defines modern luxury fashion storytelling.",
  },
  "Adria Rae": {
    "image": "https://i.ibb.co/6RD8X40x/Adria-rae.png",
    "card": "https://i.ibb.co/6RD8X40x/Adria-rae.png",
    "hero": "https://i.ibb.co/5xhWqq5S/vixen-adria-rae-3840x1600.webp",
    "portrait": "https://i.ibb.co/wh9t10yR/vixen-adria-rae-1900x1300.webp",
    "bio": "Adria Rae brings a fresh, playful energy with delicate features and expressive performances that captivate audiences worldwide.",
  },
  "Agatha Vega": {
    "image": "https://i.ibb.co/Mk6XqMpS/Agatha-Vega-4.png",
    "card": "https://i.ibb.co/Mk6XqMpS/Agatha-Vega-4.png",
    "hero": "https://i.ibb.co/1Gfyvngt/deeper-agatha-vega-3840x1600.webp",
    "portrait": "https://i.ibb.co/HTmP5gX3/blackedraw-agatha-vega-1900x1300.webp",
    "bio": "Agatha Vega dazzles with her striking Latina beauty, sensual curves, and magnetic screen presence.",
  },
  "Ailee Anne": {
    "image": "https://i.ibb.co/SXWvfgNg/Ailee-Anne.png",
    "card": "https://i.ibb.co/SXWvfgNg/Ailee-Anne.png",
    "hero": "https://i.ibb.co/4ZWpy6sk/tushy-ailee-anne-3840x1600.webp",
    "portrait": "https://i.ibb.co/GQC1XjKZ/tushy-ailee-anne-1900x1300.webp",
    "bio": "Ailee Anne is celebrated for her youthful charm, bright smile, and versatile performances.",
  },
  "Alexia Anders": {
    "image": "https://i.ibb.co/5WkM6qcQ/Alexia-Anders.png",
    "card": "https://i.ibb.co/5WkM6qcQ/Alexia-Anders.png",
    "hero": "https://i.ibb.co/TBDbqszm/tushy-alexia-anders-3840x1600.webp",
    "portrait": "https://i.ibb.co/spWs7HSb/tushy-alexia-anders-1900x1300.webp",
    "bio": "Alexia Anders captivates with exotic looks and passionate intensity.",
  },
  "Alexis Tae": {
    "image": "https://i.ibb.co/xW93spW/Alexis-Tae-3.png",
    "card": "https://i.ibb.co/xW93spW/Alexis-Tae-3.png",
    "hero": "https://i.ibb.co/jC2WBkW/slayed-alexis-tae-3840x1600.webp",
    "portrait": "https://i.ibb.co/ns0t33mm/deeper-alexis-tae-1900x1300.webp",
    "bio": "Alexis Tae shines with her athletic build, glowing skin, and dynamic presence.",
  },
  "Amber Moore": {
    "image": "https://i.ibb.co/Kp88Yswy/Amber-Moore-2.png",
    "card": "https://i.ibb.co/Kp88Yswy/Amber-Moore-2.png",
    "hero": "https://i.ibb.co/23nvsxDC/blackedraw-amber-moore-3840x1600.webp",
    "portrait": "https://i.ibb.co/SDP1bm86/blacked-amber-moore-1900x1300.webp",
    "bio": "Amber Moore delivers sweet innocence paired with sultry sophistication.",
  },
  "Ameena Green": {
    "image": "https://i.ibb.co/wN0W23ts/Ameena-Green-3.png",
    "card": "https://i.ibb.co/wN0W23ts/Ameena-Green-3.png",
    "hero": "https://i.ibb.co/bjpj5syL/blacked-ameena-green-3840x1600.webp",
    "portrait": "https://i.ibb.co/1tSjpC43/blacked-ameena-green-1900x1300.webp",
    "bio": "Ameena Green stands out with her vibrant personality and stunning natural beauty.",
  },
  "Angel Gostosa": {
    "image": "https://i.ibb.co/r2qsNnFm/Angel-Gostosa.png",
    "card": "https://i.ibb.co/r2qsNnFm/Angel-Gostosa.png",
    "hero": "https://i.ibb.co/v6Tq4V5q/blackedraw-angel-gostosa-3840x1600.webp",
    "portrait": "https://i.ibb.co/p6mPY02q/blackedraw-angel-gostosa-1900x1300.webp",
    "bio": "Angel Gostosa brings fiery passion and irresistible curves to every scene.",
  },
  "Angel Youngs": {
    "image": "https://i.ibb.co/Z65NnF7N/Angel-Youngs.png",
    "card": "https://i.ibb.co/Z65NnF7N/Angel-Youngs.png",
    "hero": "https://i.ibb.co/hFGC2TVv/vixen-angel-youngs-3840x1600.webp",
    "portrait": "https://i.ibb.co/d4zQbccD/vixen-angel-youngs-1900x1300.webp",
    "bio": "Angel Youngs is known for her angelic face and devilishly seductive style.",
  },
  "Angelina Moon": {
    "image": "https://i.ibb.co/S4WFxQNt/Angelina-Moon.png",
    "card": "https://i.ibb.co/S4WFxQNt/Angelina-Moon.png",
    "hero": "https://i.ibb.co/wh71qGtV/milfy-angelina-moon-3840x1600.webp",
    "portrait": "https://i.ibb.co/HD1nFJxT/milfy-angelina-moon-1900x1300.webp",
    "bio": "Angelina Moon enchants with ethereal beauty and graceful movements.",
  },
  "Angie Faith": {
    "image": "https://i.ibb.co/GQqpwLvQ/Angie-Faith-2.png",
    "card": "https://i.ibb.co/GQqpwLvQ/Angie-Faith-2.png",
    "hero": "https://i.ibb.co/QF6dFtbt/deeper-angie-faith-3840x1600.webp",
    "portrait": "https://i.ibb.co/q3gxWz4M/deeper-angie-faith-1900x1300.webp",
    "bio": "Angie Faith radiates pure charm and heartfelt sensuality.",
  },
  "Anissa Kate": {
    "image": "https://i.ibb.co/YTqkDr9L/Anissa-Kate-3.png",
    "card": "https://i.ibb.co/YTqkDr9L/Anissa-Kate-3.png",
    "hero": "https://i.ibb.co/n8538qLM/slayed-anissa-kate-3840x1600.webp",
    "portrait": "https://i.ibb.co/7dkPy0Nk/slayed-anissa-kate-1900x1300.jpg",
    "bio": "Anissa Kate is a sophisticated European beauty with timeless elegance.",
  },
  "Aria Lee": {
    "image": "https://i.ibb.co/dsk6vFf2/Aria-lee.png",
    "card": "https://i.ibb.co/dsk6vFf2/Aria-lee.png",
    "hero": "https://i.ibb.co/jPDrmhTM/blacked-aria-lee-3840x1600.webp",
    "portrait": "https://i.ibb.co/hxsnVd64/vixen-aria-lee-1900x1300.webp",
    "bio": "Aria Lee combines petite beauty with explosive on-screen energy.",
  },
  "Aria Taylor": {
    "image": "https://i.ibb.co/BVwBWdgH/Aria-Taylor.png",
    "card": "https://i.ibb.co/BVwBWdgH/Aria-Taylor.png",
    "hero": "https://i.ibb.co/rV3nq9D/slayed-aria-taylor-3840x1600.webp",
    "portrait": "https://i.ibb.co/cR263Wt/slayed-aria-taylor-1900x1300.webp",
    "bio": "Aria Taylor offers a perfect blend of girl-next-door appeal and high fashion.",
  },
  "Armani Black": {
    "image": "https://i.ibb.co/231Yx84s/Armani-Black.png",
    "card": "https://i.ibb.co/231Yx84s/Armani-Black.png",
    "hero": "https://i.ibb.co/GvV1WmWg/tushyraw-armani-black-3840x1600.webp",
    "portrait": "https://i.ibb.co/QvCsqCkG/tushy-armani-black-1900x1300.webp",
    "bio": "Armani Black commands attention with powerful curves and confident presence.",
  },
  "Ashby Winter": {
    "image": "https://i.ibb.co/qL5yXb7Q/Ashby-Winter.png",
    "card": "https://i.ibb.co/qL5yXb7Q/Ashby-Winter.png",
    "hero": "https://i.ibb.co/rKKWnpBH/blacked-ashby-winter-3840x1600.webp",
    "portrait": "https://i.ibb.co/4wMXSD01/blacked-ashby-winter-1900x1300.webp",
    "bio": "Ashby Winter brings cool sophistication and striking visual appeal.",
  },
  "Ashley Aixi": {
    "image": "https://i.ibb.co/1YtCCkyg/Ashley-Aixi.png",
    "card": "https://i.ibb.co/1YtCCkyg/Ashley-Aixi.png",
    "hero": "https://i.ibb.co/H0LSfTY/vixen-ashley-aixi-1920x800.webp",
    "portrait": "https://i.ibb.co/ZRLdx2tZ/vixen-ashley-aixi-950x650.webp",
    "bio": "Ashley Aixi mesmerizes with delicate Asian features and sensual grace.",
  },
  "Ashley Alexander": {
    "image": "https://i.ibb.co/MyrYYYqQ/Ashley-Alexander-2.png",
    "card": "https://i.ibb.co/MyrYYYqQ/Ashley-Alexander-2.png",
    "hero": "https://i.ibb.co/0RYXB0YL/blackedraw-ashley-alexander-3840x1600.webp",
    "portrait": "https://i.ibb.co/tpgcwvcb/deeper-ashley-alexander-1900x1300.webp",
    "bio": "Ashley Alexander stands tall with elegant proportions and refined beauty.",
  },
  "Avery Cristy": {
    "image": "https://i.ibb.co/TBN69q49/Avery-Cristy.png",
    "card": "https://i.ibb.co/TBN69q49/Avery-Cristy.png",
    "hero": "https://i.ibb.co/9k2cjkds/deeper-avery-cristy-3840x1600.webp",
    "portrait": "https://i.ibb.co/tMF7z68g/deeper-avery-cristy-1900x1300.webp",
    "bio": "Avery Cristy shines with bright charisma and stunning natural looks.",
  },
  "Azul Hermosa": {
    "image": "https://i.ibb.co/6cNtqcS8/Azul-Hermosa-2.png",
    "card": "https://i.ibb.co/6cNtqcS8/Azul-Hermosa-2.png",
    "hero": "https://i.ibb.co/m5Hpx1hj/vixen-azul-hermosa-3840x1600.webp",
    "portrait": "https://i.ibb.co/3yDvDHB2/vixen-azul-hermosa-1900x1300.webp",
    "bio": "Azul Hermosa radiates vibrant Latin energy and breathtaking curves.",
  },
  "Bailey Base": {
    "image": "https://i.ibb.co/placeholder/bailey-base.jpg",
    "card": "https://i.ibb.co/placeholder/bailey-base.jpg",
    "hero": "https://i.ibb.co/placeholder/bailey-base-hero.webp",
    "portrait": "https://i.ibb.co/placeholder/bailey-base-portrait.webp",
    "bio": "Bailey Base delivers fresh, youthful appeal with undeniable star quality.",
  },
  "Barbie Feels": {
    "image": "https://i.ibb.co/gbY9Bphn/Barbie-Feels.png",
    "card": "https://i.ibb.co/gbY9Bphn/Barbie-Feels.png",
    "hero": "https://i.ibb.co/VpzRn19m/milfy-barbie-feels-3840x1600.webp",
    "portrait": "https://i.ibb.co/7NzydSBW/milfy-barbie-feels-1900x1300.webp",
    "bio": "Barbie Feels embodies perfect doll-like beauty with glamorous flair.",
  },
  "Blake Blossom": {
    "image": "https://i.ibb.co/d94031V/Blake-Blossom.png",
    "card": "https://i.ibb.co/d94031V/Blake-Blossom.png",
    "hero": "https://i.ibb.co/DgpqP2d5/deeper-blake-blossom-3840x1600.webp",
    "portrait": "https://i.ibb.co/qwGYcS2/deeper-blake-blossom-1900x1300.webp",
    "bio": "Blake Blossom is famous for her incredible natural assets and radiant smile.",
  },
  "Britney Dutch": {
    "image": "https://i.ibb.co/fYxDqDp3/Britney-Dutch.png",
    "card": "https://i.ibb.co/fYxDqDp3/Britney-Dutch.png",
    "hero": "https://i.ibb.co/DPfsk0Q2/blackedraw-britney-dutch-3840x1600.webp",
    "portrait": "https://i.ibb.co/C5ZjFpdg/blackedraw-britney-dutch-1900x1300.webp",
    "bio": "Britney Dutch brings European elegance and playful sensuality.",
  },
  "Brooklyn Gray": {
    "image": "https://i.ibb.co/TD0kXMWv/Brooklyn-Gray.png",
    "card": "https://i.ibb.co/TD0kXMWv/Brooklyn-Gray.png",
    "hero": "https://i.ibb.co/0RhGQzhN/blacked-brooklyn-gray-3840x1600.webp",
    "portrait": "https://i.ibb.co/9k4pvRky/blacked-brooklyn-gray-1900x1300.webp",
    "bio": "Brooklyn Gray offers edgy style paired with striking beauty.",
  },
  "Catherine Knight": {
    "image": "https://i.ibb.co/WvHN81dX/Catherine-Knight-2.png",
    "card": "https://i.ibb.co/WvHN81dX/Catherine-Knight-2.png",
    "hero": "https://i.ibb.co/Zp3Sz3Wg/tushy-catherine-knight-3840x1600.webp",
    "portrait": "https://i.ibb.co/3xR4Xhz/tushy-catherine-knight-1900x1300.webp",
    "bio": "Catherine Knight commands the screen with powerful presence and elegance.",
  },
  "Cecelia Taylor": {
    "image": "https://i.ibb.co/ymFNvmR1/Cecelia-Taylor.png",
    "card": "https://i.ibb.co/ymFNvmR1/Cecelia-Taylor.png",
    "hero": "https://i.ibb.co/nMtSnFdM/slayed-cecelia-taylor-3840x1600.webp",
    "portrait": "https://i.ibb.co/vxhSnMZr/slayed-cecelia-taylor-1900x1300.webp",
    "bio": "Cecelia Taylor enchants with sweet features and genuine charm.",
  },
  "Chanel Camryn": {
    "image": "https://i.ibb.co/VcWQsMGR/Chanel-Camryn-3.png",
    "card": "https://i.ibb.co/VcWQsMGR/Chanel-Camryn-3.png",
    "hero": "https://i.ibb.co/cS6mkCjz/deeper-chanel-camryn-3840x1600.webp",
    "portrait": "https://i.ibb.co/JW7hRGc9/deeper-chanel-camryn-1900x1300.webp",
    "bio": "Chanel Camryn blends luxury appeal with raw sensuality.",
  },
  "Cherie DeVille": {
    "image": "https://i.ibb.co/DDNKjn4W/profile-001.webp",
    "card": "https://i.ibb.co/DDNKjn4W/profile-001.webp",
    "hero": "https://i.ibb.co/spXbQVjF/tushy-cherie-deville-3840x1600.webp",
    "portrait": "https://i.ibb.co/S40zZ4CV/blacked-cherie-deville-1900x1300.jpg",
    "bio": "Cherie DeVille is a veteran star known for timeless beauty and professionalism.",
  },
  "Chloe Amour": {
    "image": "https://i.ibb.co/zVFTXw2p/Chloe-Amour.png",
    "card": "https://i.ibb.co/zVFTXw2p/Chloe-Amour.png",
    "hero": "https://i.ibb.co/hFSpbFPD/blackedraw-chloe-amour-3840x1600.webp",
    "portrait": "https://i.ibb.co/4R5sr9xm/blackedraw-chloe-amour-1900x1300.webp",
    "bio": "Chloe Amour radiates warm Latina sensuality and graceful movement.",
  },
  "Chloe Surreal": {
    "image": "https://i.ibb.co/JRSQWBrt/Chloe-Surreal.png",
    "card": "https://i.ibb.co/JRSQWBrt/Chloe-Surreal.png",
    "hero": "https://i.ibb.co/bgFhvRgD/blackedraw-chloe-surreal-3840x1600.webp",
    "portrait": "https://i.ibb.co/JF5jC45T/blackedraw-63022-3840x2160.webp",
    "bio": "Chloe Surreal captivates with dreamlike beauty and artistic expression.",
  },
  "Christy White": {
    "image": "https://i.ibb.co/wF2HRH6V/Christy-White.png",
    "card": "https://i.ibb.co/wF2HRH6V/Christy-White.png",
    "hero": "https://i.ibb.co/8t3t4Xf/vixen-christy-white-1920x800.webp",
    "portrait": "https://i.ibb.co/9HcHJR6f/vixen-christy-white-950x650.webp",
    "bio": "Christy White offers pure, bright appeal with natural elegance.",
  },
  "Coco Lovelock": {
    "image": "https://i.ibb.co/nswGpHjs/Co-Co-Lovelock.png",
    "card": "https://i.ibb.co/nswGpHjs/Co-Co-Lovelock.png",
    "hero": "https://i.ibb.co/3mhbKsMY/tushy-coco-lovelock-3840x1600.webp",
    "portrait": "https://i.ibb.co/LDdtdp5V/tushy-coco-lovelock-1900x1300.webp",
    "bio": "Coco Lovelock is adored for her petite frame and bubbly personality.",
  },
  "Codi Vore": {
    "image": "https://i.ibb.co/placeholder/codi-vore.jpg",
    "card": "https://i.ibb.co/placeholder/codi-vore.jpg",
    "hero": "https://i.ibb.co/placeholder/codi-vore-hero.webp",
    "portrait": "https://i.ibb.co/placeholder/codi-vore-portrait.webp",
    "bio": "Codi Vore is known for her voluptuous figure and warm, inviting presence.",
  },
  "Dana Vespoli": {
    "image": "https://i.ibb.co/SXvFMgNj/Dana-Vespoli.png",
    "card": "https://i.ibb.co/SXvFMgNj/Dana-Vespoli.png",
    "hero": "https://i.ibb.co/8D8dN1q2/milfy-dana-vespoli-3840x1600.webp",
    "portrait": "https://i.ibb.co/GfswMwjQ/milfy-dana-vespoli-1900x1300.webp",
    "bio": "Dana Vespoli combines experience, sophistication, and enduring appeal.",
  },
  "Dani Daniels": {
    "image": "https://i.ibb.co/MDMNgqNd/Dani-Daniels.png",
    "card": "https://i.ibb.co/MDMNgqNd/Dani-Daniels.png",
    "hero": "https://i.ibb.co/8LzYht2D/blacked-dani-daniels-3840x1600.jpg",
    "portrait": "https://i.ibb.co/mrVq0qhx/blacked-dani-daniels-1900x1300.jpg",
    "bio": "Dani Daniels is a legendary beauty celebrated for artistic vision and charisma.",
  },
  "Della Cate": {
    "image": "https://i.ibb.co/9HKH3WnX/Della-Cate-2.png",
    "card": "https://i.ibb.co/9HKH3WnX/Della-Cate-2.png",
    "hero": "https://i.ibb.co/fzyjTdvp/blacked-della-cate-3840x1600.webp",
    "portrait": "https://i.ibb.co/r25HN0BZ/blacked-della-cate-1900x1300.webp",
    "bio": "Della Cate brings fresh innocence and delicate charm.",
  },
  "Demi Hawks": {
    "image": "https://i.ibb.co/r22G5yJc/Demi-Hawks-3.png",
    "card": "https://i.ibb.co/r22G5yJc/Demi-Hawks-3.png",
    "hero": "https://i.ibb.co/bjY0G6gn/deeper-demi-hawks-3840x1600.webp",
    "portrait": "https://i.ibb.co/ZRWQcdTW/deeper-demi-hawks-1900x1300.webp",
    "bio": "Demi Hawks shines with youthful glow and captivating eyes.",
  },
  "Dolly Orchid": {
    "image": "https://i.ibb.co/gFF92n54/Dolly-Orchid-3.png",
    "card": "https://i.ibb.co/gFF92n54/Dolly-Orchid-3.png",
    "hero": "https://i.ibb.co/mC5nsGB8/blacked-dolly-orchid-3840x1600.webp",
    "portrait": "https://i.ibb.co/JRdzRdYn/tushy-dolly-orchid-1900x1300.webp",
    "bio": "Dolly Orchid offers unique exotic beauty and artistic flair.",
  },
  "Eliza Ibarra": {
    "image": "https://i.ibb.co/HTVCbYCQ/Eliza-Ibarra-3.png",
    "card": "https://i.ibb.co/HTVCbYCQ/Eliza-Ibarra-3.png",
    "hero": "https://i.ibb.co/HTVCbYCQ/Eliza-Ibarra-3.png",
    "portrait": "https://i.ibb.co/M5ScxZgd/slayed-eliza-ibarra-1900x1300.webp",
    "bio": "Eliza Ibarra mesmerizes with tall, slender beauty and intense performances.",
  },
  "Ella Hughes": {
    "image": "https://i.ibb.co/6JYzsqPC/Ella-Hughes-2.png",
    "card": "https://i.ibb.co/6JYzsqPC/Ella-Hughes-2.png",
    "hero": "https://i.ibb.co/2BYWFML/blackedraw-ella-hughes-3840x1600.webp",
    "portrait": "https://i.ibb.co/fVgpSfmd/blackedraw-ella-hughes-1900x1300.webp",
    "bio": "Ella Hughes brings classic British charm and fiery redhead energy.",
  },
  "Ellie Leen": {
    "image": "https://i.ibb.co/F4yDF9N9/Ellie-Leen.png",
    "card": "https://i.ibb.co/F4yDF9N9/Ellie-Leen.png",
    "hero": "https://i.ibb.co/v6Mqyd8Q/vixen-ellie-leen-1920x800.webp",
    "portrait": "https://i.ibb.co/C3x0tLwQ/vixen-ellie-leen-950x650.webp",
    "bio": "Ellie Leen is loved for her adorable features and gentle sensuality.",
  },
  "Ellie Nova": {
    "image": "https://i.ibb.co/v63KMVcd/Ellie-Nova.png",
    "card": "https://i.ibb.co/v63KMVcd/Ellie-Nova.png",
    "hero": "https://i.ibb.co/DPr3TNdd/blackedraw-ellie-nova-3840x1600.webp",
    "portrait": "https://i.ibb.co/HD89y6q5/blackedraw-ellie-nova-1900x1300.webp",
    "bio": "Ellie Nova explodes with vibrant personality and stunning visuals.",
  },
  "Elly Clutch": {
    "image": "https://i.ibb.co/gbLKkhWQ/62372907-003-f761.jpg",
    "card": "https://i.ibb.co/gbLKkhWQ/62372907-003-f761.jpg",
    "hero": "https://i.ibb.co/zyKs2wD/beautiful-sexy-girls.jpg",
    "portrait": "https://i.ibb.co/twgRshz1/Rewarding-You-1-Elly-Clutch-medium-0020.jpg",
    "bio": "Elly Clutch captivates with curvy perfection and confident style.",
  },
  "Elsa Jean": {
    "image": "https://i.ibb.co/2HCfVFn/Emilly-willis.png",
    "card": "https://i.ibb.co/2HCfVFn/Emilly-willis.png",
    "hero": "https://i.ibb.co/PzgXfhFp/vixen-elsa-jean-3840x1600.webp",
    "portrait": "https://i.ibb.co/vxkg6Cs1/vixen-elsa-jean-1900x1300.webp",
    "bio": "Elsa Jean is the ultimate blonde sweetheart with a playful spirit.",
  },
  "Emily Willis": {
    "image": "https://i.ibb.co/4ZxDnbxm/Emily-Willis-4.png",
    "card": "https://i.ibb.co/4ZxDnbxm/Emily-Willis-4.png",
    "hero": "https://i.ibb.co/mFPgvBtp/tushy-emily-willis-3840x1600.webp",
    "portrait": "https://i.ibb.co/TByfy3W0/tushy-emily-willis-1900x1300.webp",
    "bio": "Emily Willis combines exotic beauty with fearless creativity.",
  },
  "Emiri Momota": {
    "image": "https://i.ibb.co/rGwz2K4g/Emiri-Momota.png",
    "card": "https://i.ibb.co/rGwz2K4g/Emiri-Momota.png",
    "hero": "https://i.ibb.co/Fb2BFFsw/vixen-emiri-momota-3840x1600.webp",
    "portrait": "https://i.ibb.co/Gfgt8Jwy/vixen-emiri-momota-1900x1300.webp",
    "bio": "Emiri Momota brings delicate Japanese elegance and refined sensuality.",
  },
  "Emma Rosie": {
    "image": "https://i.ibb.co/8n3P867Z/Emma-Rosie-3.png",
    "card": "https://i.ibb.co/8n3P867Z/Emma-Rosie-3.png",
    "hero": "https://i.ibb.co/1Jfzc5jp/deeper-emma-rosie-3840x1600.webp",
    "portrait": "https://i.ibb.co/7ttT7q4y/deeper-emma-rosie-1900x1300.webp",
    "bio": "Emma Rosie delights with youthful innocence and sparkling eyes.",
  },
  "Eva Elfie": {
    "image": "https://i.ibb.co/PZc3WtHZ/Eva-Elfie.png",
    "card": "https://i.ibb.co/PZc3WtHZ/Eva-Elfie.png",
    "hero": "https://i.ibb.co/yFTbkhGs/vixen-eva-elfie-3840x1600.webp",
    "portrait": "https://i.ibb.co/CKvwN8Vr/slayed-eva-elfie-1900x1300.webp",
    "bio": "Eva Elfie is adored globally for her angelic beauty, perfect proportions, and charismatic performances.",
  },
  "Eva Generosi": {
    "image": "https://i.ibb.co/yF1TD3Xk/Eva-Generosi.png",
    "card": "https://i.ibb.co/yF1TD3Xk/Eva-Generosi.png",
    "hero": "https://i.ibb.co/dsm5JpQT/vixen-eva-generosi-1920x800.webp",
    "portrait": "https://i.ibb.co/jvjvz0Pq/tushy-eva-generosi-1900x1300.webp",
    "bio": "Eva Generosi offers sophisticated European allure and natural grace.",
  },
  "Eve Sweet": {
    "image": "https://i.ibb.co/BVb5T7d8/Eve-Sweet-4.png",
    "card": "https://i.ibb.co/BVb5T7d8/Eve-Sweet-4.png",
    "hero": "https://i.ibb.co/rR0zY5v0/slayed-eve-sweet-3840x1600.webp",
    "portrait": "https://i.ibb.co/rR0zY5v0/slayed-eve-sweet-3840x1600.webp",
    "bio": "Eve Sweet tempts with sweet features and irresistible charm.",
  },
  "Freya Parker": {
    "image": "https://i.ibb.co/1tWHCS3G/Freya-Parker.png",
    "card": "https://i.ibb.co/1tWHCS3G/Freya-Parker.png",
    "hero": "https://i.ibb.co/Y7dyd49D/slayed-freya-parker-3840x1600.webp",
    "portrait": "https://i.ibb.co/gLchM5Qq/slayed-freya-parker-1900x1300.webp",
    "bio": "Freya Parker impresses with tall, athletic beauty and strong presence.",
  },
  "Gal Ritchie": {
    "image": "https://i.ibb.co/67Sg3GwP/Gal-Ritchie.png",
    "card": "https://i.ibb.co/67Sg3GwP/Gal-Ritchie.png",
    "hero": "https://i.ibb.co/zHhsc43K/deeper-gal-ritchie-3840x1600.webp",
    "portrait": "https://i.ibb.co/Hp2qCvqv/deeper-gal-ritchie-1900x1300.webp",
    "bio": "Gal Ritchie brings unique style and captivating screen energy.",
  },
  "Gianna Dior": {
    "image": "https://i.ibb.co/3Y8Myqmv/Gianna-Dior-3.png",
    "card": "https://i.ibb.co/3Y8Myqmv/Gianna-Dior-3.png",
    "hero": "https://i.ibb.co/0d1t1vt/blackedraw-gianna-dior-3840x1600.webp",
    "portrait": "https://i.ibb.co/PzQnbsKb/blackedraw-gianna-dior-1900x1300.webp",
    "bio": "Gianna Dior is a premium star known for flawless beauty and elite performances.",
  },
  "Hailey Rose": {
    "image": "https://i.ibb.co/3YY67Zwc/86448286-027-eb51.jpg",
    "card": "https://i.ibb.co/3YY67Zwc/86448286-027-eb51.jpg",
    "hero": "https://i.ibb.co/5WrV7Qx6/10118208-003-444b.jpg",
    "portrait": "https://i.ibb.co/39jD9s1B/10118208-002-91e7.jpg",
    "bio": "Hailey Rose blooms with fresh beauty and vibrant personality.",
  },
  "Hazel Heart": {
    "image": "https://i.ibb.co/NbNKyjm/Hazel-Heart.png",
    "card": "https://i.ibb.co/NbNKyjm/Hazel-Heart.png",
    "hero": "https://i.ibb.co/p6zhFsB0/slayed-hazel-heart-3840x1600.webp",
    "portrait": "https://i.ibb.co/DPZrqZ32/slayed-hazel-heart-1900x1300.webp",
    "bio": "Hazel Heart warms hearts with gentle beauty and sincere performances.",
  },
  "Hazel Moore": {
    "image": "https://i.ibb.co/WpD8hXPs/Hazel-Moore-4.png",
    "card": "https://i.ibb.co/WpD8hXPs/Hazel-Moore-4.png",
    "hero": "https://i.ibb.co/rKTFy1mV/tushy-hazel-moore-3840x1600.webp",
    "portrait": "https://i.ibb.co/XZh5rv2s/tushy-hazel-moore-1900x1300.webp",
    "bio": "Hazel Moore offers natural charm and endearing presence.",
  },
  "Isa Bella": {
    "image": "https://i.ibb.co/ksLtHpLk/Isa-Bella.png",
    "card": "https://i.ibb.co/ksLtHpLk/Isa-Bella.png",
    "hero": "https://i.ibb.co/849MncK6/vixen-isa-bella-1920x800.webp",
    "portrait": "https://i.ibb.co/SDCVT0fs/vixen-isa-bella-950x650.webp",
    "bio": "Isa Bella enchants with exotic appeal and passionate delivery.",
  },
  "Janice Griffith": {
    "image": "https://i.ibb.co/jPb1PG8j/Janice-Griffith.png",
    "card": "https://i.ibb.co/jPb1PG8j/Janice-Griffith.png",
    "hero": "https://i.ibb.co/HDrxG9yd/deeper-janice-griffith-3840x1600.webp",
    "portrait": "https://i.ibb.co/ccXNSNr5/deeper-janice-griffith-1900x1300.webp",
    "bio": "Janice Griffith is a petite powerhouse with infectious energy.",
  },
  "Jasmine Sherni": {
    "image": "https://i.ibb.co/q3MJFz8p/65592892-001-edc7.jpg",
    "card": "https://i.ibb.co/q3MJFz8p/65592892-001-edc7.jpg",
    "hero": "https://i.ibb.co/HLTPjh7J/1.jpg",
    "portrait": "https://i.ibb.co/HLTPjh7J/1.jpg",
    "bio": "Jasmine Sherni brings fierce beauty and bold sensuality.",
  },
  "Jazmin Luv": {
    "image": "https://i.ibb.co/qF5RrXR6/Jazmin-Luv.png",
    "card": "https://i.ibb.co/qF5RrXR6/Jazmin-Luv.png",
    "hero": "https://i.ibb.co/N6RKnc35/blacked-jazmin-luv-3840x1600.webp",
    "portrait": "https://i.ibb.co/7dbcDn7Y/deeper-jazmin-luv-1900x1300.webp",
    "bio": "Jazmin Luv radiates love and playful seduction.",
  },
  "Jia Lissa": {
    "image": "https://i.ibb.co/MkCKj00H/Jia-Lissa-4.png",
    "card": "https://i.ibb.co/MkCKj00H/Jia-Lissa-4.png",
    "hero": "https://i.ibb.co/C3LBCczW/deeper-jia-lissa-3840x1600.webp",
    "portrait": "https://i.ibb.co/6cFj68Lm/deeper-jia-lissa-1900x1300.webp",
    "bio": "Jia Lissa is renowned for her fiery red hair and stunning Eastern European features.",
  },
  "Joanna Wei": {
    "image": "https://i.ibb.co/6cwHWnnj/Joanna-Wei.png",
    "card": "https://i.ibb.co/6cwHWnnj/Joanna-Wei.png",
    "hero": "https://i.ibb.co/7xvgHP0f/vixen-joanna-wei-1920x800.webp",
    "portrait": "https://i.ibb.co/XkFygmRr/vixen-joanna-wei-950x650.webp",
    "bio": "Joanna Wei captivates with refined Asian beauty and graceful style.",
  },
  "Julia James": {
    "image": "https://i.ibb.co/kzs3xwV/43973329-003-e9b4.jpg",
    "card": "https://i.ibb.co/kzs3xwV/43973329-003-e9b4.jpg",
    "hero": "https://i.ibb.co/4ZMhcXPw/72525554-002-edf4.jpg",
    "portrait": "https://i.ibb.co/4ZMhcXPw/72525554-002-edf4.jpg",
    "bio": "Julia James delivers classic beauty and confident performances.",
  },
  "Katana Kombat": {
    "image": "https://i.ibb.co/wr89kB2Z/31079874-007-880a.jpg",
    "card": "https://i.ibb.co/wr89kB2Z/31079874-007-880a.jpg",
    "hero": "https://i.ibb.co/PZgyN4b9/61040018-029-9ac7-1.jpg",
    "portrait": "https://i.ibb.co/PZgyN4b9/61040018-029-9ac7-1.jpg",
    "bio": "Katana Kombat fuses martial elegance with explosive sensuality.",
  },
  "Katie Kush": {
    "image": "https://i.ibb.co/gZf6ZfZL/Katie-Kush-3.png",
    "card": "https://i.ibb.co/gZf6ZfZL/Katie-Kush-3.png",
    "hero": "https://i.ibb.co/vvvG0Rfw/deeper-katie-kush-3840x1600.webp",
    "portrait": "https://i.ibb.co/spJKSS1x/deeper-katie-kush-1900x1300.webp",
    "bio": "Katie Kush is known for flexibility, energy, and bright appeal.",
  },
  "Kayley Gunner": {
    "image": "https://i.ibb.co/C5m5pJyZ/Kayley-Gunner.png",
    "card": "https://i.ibb.co/C5m5pJyZ/Kayley-Gunner.png",
    "hero": "https://i.ibb.co/XxKhNWn6/blackedraw-kayley-gunner-3840x1600.webp",
    "portrait": "https://i.ibb.co/G6Mn045/blackedraw-kayley-gunner-1900x1300.webp",
    "bio": "Kayley Gunner offers military-precision beauty and commanding presence.",
  },
  "Kelly Collins": {
    "image": "https://i.ibb.co/yF78XcxW/Kelly-Collins.png",
    "card": "https://i.ibb.co/yF78XcxW/Kelly-Collins.png",
    "hero": "https://i.ibb.co/4w5ZqPY8/blacked-kelly-collins-3840x1600.webp",
    "portrait": "https://i.ibb.co/xqKRYB3X/tushy-kelly-collins-1900x1300.webp",
    "bio": "Kelly Collins shines with elegant European features.",
  },
  "Kendra Spade": {
    "image": "https://i.ibb.co/hxx8S5Mn/k-ENDRA-SPADE-2.png",
    "card": "https://i.ibb.co/hxx8S5Mn/k-ENDRA-SPADE-2.png",
    "hero": "https://i.ibb.co/XfHJ74DB/tushy-kendra-spade-3840x1600.webp",
    "portrait": "https://i.ibb.co/gLs5bjL3/blackedraw-kendra-spade-1900x1300.webp",
    "bio": "Kendra Spade brings exotic Asian-American beauty and intense passion.",
  },
  "Kimmy Kimm": {
    "image": "https://i.ibb.co/V0bb14Ns/Kimmy-Kimm-3.png",
    "card": "https://i.ibb.co/V0bb14Ns/Kimmy-Kimm-3.png",
    "hero": "https://i.ibb.co/RkDypyCt/deeper-kimmy-kimm-3840x1600.webp",
    "portrait": "https://i.ibb.co/HTnxgfGW/deeper-kimmy-kimm-1900x1300.webp",
    "bio": "Kimmy Kimm delights with petite charm and vibrant personality.",
  },
  "Kwini Kim": {
    "image": "https://i.ibb.co/QF1xmRvq/Kwini.png",
    "card": "https://i.ibb.co/QF1xmRvq/Kwini.png",
    "hero": "https://i.ibb.co/1frs7DL6/tushy-kwini-3840x1600.webp",
    "portrait": "https://i.ibb.co/V0BpR1PM/tushy-kwini-1900x1300.webp",
    "bio": "Kwini Kim stands out with unique beauty and magnetic appeal.",
  },
  "Kylie Rocket": {
    "image": "https://i.ibb.co/5gYVYTvf/Kylie-Rocket.png",
    "card": "https://i.ibb.co/5gYVYTvf/Kylie-Rocket.png",
    "hero": "https://i.ibb.co/xqdWw7Kv/blacked-kylie-rocket-3840x1600.webp",
    "portrait": "https://i.ibb.co/CKS6F6nj/blacked-kylie-rocket-1900x1300.webp",
    "bio": "Kylie Rocket soars with youthful energy and stunning visuals.",
  },
  "Lana Rhoades": {
    "image": "https://i.ibb.co/7ttmZmvK/Lana-Rhoades-2.png",
    "card": "https://i.ibb.co/7ttmZmvK/Lana-Rhoades-2.png",
    "hero": "https://i.ibb.co/cKG5rRfB/vixen-lana-rhoades-3840x1600.webp",
    "portrait": "https://i.ibb.co/PZrZ3NHL/vixen-lana-rhoades-1900x1300.webp",
    "bio": "Lana Rhoades is an icon of modern adult entertainment with unparalleled beauty and star power.",
  },
  "Lana Smalls": {
    "image": "https://i.ibb.co/KjKGrKNx/Lana-Smalls.png",
    "card": "https://i.ibb.co/KjKGrKNx/Lana-Smalls.png",
    "hero": "https://i.ibb.co/JVgyfsS/deeper-lana-smalls-3840x1600.webp",
    "portrait": "https://i.ibb.co/spSKCdvB/deeper-lana-smalls-1900x1300.webp",
    "bio": "Lana Smalls offers compact perfection and endless charm.",
  },
  "Leana Lovings": {
    "image": "https://i.ibb.co/FbDBSHQc/Leana-Lovings.png",
    "card": "https://i.ibb.co/FbDBSHQc/Leana-Lovings.png",
    "hero": "https://i.ibb.co/FbTDvPH6/deeper-leana-lovings-3840x1600.webp",
    "portrait": "https://i.ibb.co/My1WN04y/blackedraw-leana-lovings-1900x1300.webp",
    "bio": "Leana Lovings wins hearts with genuine warmth and beauty.",
  },
  "Lexi Lore": {
    "image": "https://i.ibb.co/p6GZbC6q/Lexi-Lore.png",
    "card": "https://i.ibb.co/p6GZbC6q/Lexi-Lore.png",
    "hero": "https://i.ibb.co/pBSWQZQd/deeper-lexi-lore-3840x1600.webp",
    "portrait": "https://i.ibb.co/bjJHZtsY/deeper-lexi-lore-1900x1300.webp",
    "bio": "Lexi Lore captivates with pale beauty and intense performances.",
  },
  "Lexi Luna": {
    "image": "https://i.ibb.co/whVJw67S/Lexi-Luna.png",
    "card": "https://i.ibb.co/whVJw67S/Lexi-Luna.png",
    "hero": "https://i.ibb.co/YvyX6YZ/milfy-lexi-luna-3840x1600.webp",
    "portrait": "https://i.ibb.co/hPnTnTC/milfy-lexi-luna-1900x1300.webp",
    "bio": "Lexi Luna brings mature sophistication and voluptuous appeal.",
  },
  "Lexi Smith": {
    "image": "https://i.ibb.co/TMbjtNjh/Lexi-Smith.png",
    "card": "https://i.ibb.co/TMbjtNjh/Lexi-Smith.png",
    "hero": "https://i.ibb.co/yc4SKw7J/milfy-lexi-smith-3840x1600.webp",
    "portrait": "https://i.ibb.co/mFbfMzLc/milfy-lexi-smith-1900x1300.webp",
    "bio": "Lexi Smith offers classic American beauty and approachable charm.",
  },
  "Lia Lin": {
    "image": "https://i.ibb.co/wrr1qsxR/Lia-Lin-2.png",
    "card": "https://i.ibb.co/wrr1qsxR/Lia-Lin-2.png",
    "hero": "https://i.ibb.co/zhcXkqDv/blacked-lia-lin-3840x1600.webp",
    "portrait": "https://i.ibb.co/rKq0fJsS/blackedraw-lia-lin-1900x1300.webp",
    "bio": "Lia Lin enchants with elegant Asian features and sensual grace.",
  },
  "Lilly Bell": {
    "image": "https://i.ibb.co/KptsjZTN/Lilly-Bell-4.png",
    "card": "https://i.ibb.co/KptsjZTN/Lilly-Bell-4.png",
    "hero": "https://i.ibb.co/Z6xrvvZr/vixen-lilly-bell-3840x1600.webp",
    "portrait": "https://i.ibb.co/fV6Lcznj/vixen-lilly-bell-1900x1300.webp",
    "bio": "Lilly Bell rings with fresh, natural beauty and sweet demeanor.",
  },
  "Little Angel": {
    "image": "https://i.ibb.co/mrw2KFmZ/Little-Angel.png",
    "card": "https://i.ibb.co/mrw2KFmZ/Little-Angel.png",
    "hero": "https://i.ibb.co/9H4CvHk5/vixen-little-angel-3840x1600.webp",
    "portrait": "https://i.ibb.co/8Dw5FcCH/slayed-little-angel-1900x1300.webp",
    "bio": "Little Angel embodies delicate innocence and heavenly appeal.",
  },
  "Little Caprice": {
    "image": "https://i.ibb.co/7xdvY26Q/Little-Caprice.png",
    "card": "https://i.ibb.co/7xdvY26Q/Little-Caprice.png",
    "hero": "https://i.ibb.co/hx7JY640/blacked-little-caprice-3840x1600.jpg",
    "portrait": "https://i.ibb.co/5xh6WYsg/blacked-little-caprice-1900x1300.jpg",
    "bio": "Little Caprice is a European icon known for elegance and passion.",
  },
  "Liya Silver": {
    "image": "https://i.ibb.co/fz8kL8pj/Liya-Silver-3.png",
    "card": "https://i.ibb.co/fz8kL8pj/Liya-Silver-3.png",
    "hero": "https://i.ibb.co/ycTZPvjd/tushy-liya-silver-3840x1600.webp",
    "portrait": "https://i.ibb.co/7NXRjPDr/tushy-liya-silver-1900x1300.webp",
    "bio": "Liya Silver impresses with striking beauty and powerful presence.",
  },
  "Liz Jordan": {
    "image": "https://i.ibb.co/cXF70qw8/Liz-Jordan-2.png",
    "card": "https://i.ibb.co/cXF70qw8/Liz-Jordan-2.png",
    "hero": "https://i.ibb.co/m5cgrYDz/deeper-liz-jordan-3840x1600.webp",
    "portrait": "https://i.ibb.co/tPnKxyrG/deeper-liz-jordan-1900x1300.webp",
    "bio": "Liz Jordan offers fresh appeal and energetic performances.",
  },
  "Lucy Mochi": {
    "image": "https://i.ibb.co/Y4bgrn8b/Lucy-Mochi.png",
    "card": "https://i.ibb.co/Y4bgrn8b/Lucy-Mochi.png",
    "hero": "https://i.ibb.co/W4qg3ZtW/vixen-lucy-mochi-3840x1600.webp",
    "portrait": "https://i.ibb.co/0RFCSh0k/vixen-lucy-mochi-1900x1300.webp",
    "bio": "Lucy Mochi brings sweet Asian charm and delightful presence.",
  },
  "Lulu Chu": {
    "image": "https://i.ibb.co/jPXdfBcS/Lulu-chu.png",
    "card": "https://i.ibb.co/jPXdfBcS/Lulu-chu.png",
    "hero": "https://i.ibb.co/BHScSt1F/tushy-lulu-chu-3840x1600.webp",
    "portrait": "https://i.ibb.co/nMsGtcJD/vixen-lulu-chu-1900x1300.webp",
    "bio": "Lulu Chu is beloved for her tiny frame and massive on-screen impact.",
  },
  "Matty Mila Perez": {
    "image": "https://i.ibb.co/TxJ59BKS/Matty-Mila-Perez-3.png",
    "card": "https://i.ibb.co/TxJ59BKS/Matty-Mila-Perez-3.png",
    "hero": "https://i.ibb.co/Xxv5N2vg/milfy-matty-mila-perez-3840x1600.webp",
    "portrait": "https://i.ibb.co/n8qBcYXZ/milfy-matty-mila-perez-1900x1300.webp",
    "bio": "Matty Mila Perez radiates Latin fire and vibrant beauty.",
  },
  "Megan Longoria": {
    "image": "https://i.ibb.co/BV22jTvT/Megan-Longoria-2.png",
    "card": "https://i.ibb.co/BV22jTvT/Megan-Longoria-2.png",
    "hero": "https://i.ibb.co/FkXSS35T/tushyraw-megan-longoria-3840x1600.webp",
    "portrait": "https://i.ibb.co/s9BGXx3r/tushyraw-megan-longoria-1900x1300.webp",
    "bio": "Megan Longoria offers tall, statuesque beauty.",
  },
  "Megan Mistakes": {
    "image": "https://i.ibb.co/Ndn9b0VF/Megan-Mistakes-2.png",
    "card": "https://i.ibb.co/Ndn9b0VF/Megan-Mistakes-2.png",
    "hero": "https://i.ibb.co/3yKRyC1V/vixen-megan-mistakes-1920x800.webp",
    "portrait": "https://i.ibb.co/ks715m3D/blackedraw-megan-mistakes-1900x1300.webp",
    "bio": "Megan Mistakes brings fun, adventurous energy.",
  },
  "Melanie Marie": {
    "image": "https://i.ibb.co/bgCyXNDX/Melanie-Marie-6.png",
    "card": "https://i.ibb.co/bgCyXNDX/Melanie-Marie-6.png",
    "hero": "https://i.ibb.co/fV9KcJ0Q/slayed-melanie-marie-3840x1600.webp",
    "portrait": "https://i.ibb.co/kggxw7h8/deeper-melanie-marie-1900x1300.webp",
    "bio": "Melanie Marie shines with warm, inviting beauty.",
  },
  "Millie Morgan": {
    "image": "https://i.ibb.co/JwqHSqxV/Millie-Morgan.png",
    "card": "https://i.ibb.co/JwqHSqxV/Millie-Morgan.png",
    "hero": "https://i.ibb.co/CpZCv5k2/milfy-millie-morgan-3840x1600.webp",
    "portrait": "https://i.ibb.co/Rk4P9YTm/milfy-millie-morgan-1900x1300.webp",
    "bio": "Millie Morgan delivers classic appeal and strong performances.",
  },
  "Molly Little": {
    "image": "https://i.ibb.co/CptsQMT0/molly-little-sweet-tooth-vixen-05.jpg",
    "card": "https://i.ibb.co/CptsQMT0/molly-little-sweet-tooth-vixen-05.jpg",
    "hero": "https://i.ibb.co/84QMYYqc/deeper-molly-little-3840x1600.webp",
    "portrait": "https://i.ibb.co/QvW0gGCp/deeper-molly-little-1900x1300.webp",
    "bio": "Molly Little charms with petite sweetness and big talent.",
  },
  "Nikki Nicole": {
    "image": "https://i.ibb.co/84Tk745F/Nikki-Nicole.png",
    "card": "https://i.ibb.co/84Tk745F/Nikki-Nicole.png",
    "hero": "https://i.ibb.co/JjVF9GnM/blackedraw-nikki-nicole-3840x1600.webp",
    "portrait": "https://i.ibb.co/0ppccLCs/blackedraw-nikki-nicole-1900x1300.webp",
    "bio": "Nikki Nicole stands out with bold curves and confident style.",
  },
  "Octavia Red": {
    "image": "https://i.ibb.co/r24Lksm0/Octavia-Red.png",
    "card": "https://i.ibb.co/r24Lksm0/Octavia-Red.png",
    "hero": "https://i.ibb.co/TMv8pbSV/blackedraw-octavia-red-3840x1600.webp",
    "portrait": "https://i.ibb.co/ZznMP2c5/blackedraw-octavia-red-1900x1300.webp",
    "bio": "Octavia Red ignites with fiery red hair and passionate energy.",
  },
  "Queenie Sateen": {
    "image": "https://i.ibb.co/k6gJL0hs/Queenie-Sateen.png",
    "card": "https://i.ibb.co/k6gJL0hs/Queenie-Sateen.png",
    "hero": "https://i.ibb.co/0pMnyk3j/slayed-queenie-sateen-3840x1600.webp",
    "portrait": "https://i.ibb.co/yFgGCM84/deeper-queenie-sateen-1900x1300.webp",
    "bio": "Queenie Sateen reigns with glamorous, queen-like presence.",
  },
  "Rae Lil Black": {
    "image": "https://i.ibb.co/3YQGy8JQ/Rae-Lil-Black-2.png",
    "card": "https://i.ibb.co/3YQGy8JQ/Rae-Lil-Black-2.png",
    "hero": "https://i.ibb.co/VY7KQCBv/blackedraw-rae-lil-black-3840x1600.webp",
    "portrait": "https://i.ibb.co/SXzHfGRk/blackedraw-rae-lil-black-1900x1300.webp",
    "bio": "Rae Lil Black blends cute and seductive with perfect precision.",
  },
  "Reina Ohara": {
    "image": "https://i.ibb.co/N2j68y4J/Reina-Ohara.png",
    "card": "https://i.ibb.co/N2j68y4J/Reina-Ohara.png",
    "hero": "https://i.ibb.co/5W1q3LMp/tushy-reina-ohara-3840x1600.webp",
    "portrait": "https://i.ibb.co/QjCjFGDZ/tushy-reina-ohara-1900x1300.webp",
    "bio": "Reina Ohara offers elegant Japanese beauty.",
  },
  "Rikako Katayama": {
    "image": "https://i.ibb.co/9HSWFJRm/Rikako-Katayama-2.png",
    "card": "https://i.ibb.co/9HSWFJRm/Rikako-Katayama-2.png",
    "hero": "https://i.ibb.co/Lzq1P7x7/vixen-rikako-katayama-3840x1600.webp",
    "portrait": "https://i.ibb.co/Qv8qKmjt/blackedraw-rikako-katayama-1900x1300.webp",
    "bio": "Rikako Katayama brings refined Japanese artistry.",
  },
  "Riley Reid": {
    "image": "https://i.ibb.co/Zp7pf9mz/Riley-Reid-3.png",
    "card": "https://i.ibb.co/Zp7pf9mz/Riley-Reid-3.png",
    "hero": "https://i.ibb.co/mrhThDyR/blackedraw-riley-reid-3840x1600.webp",
    "portrait": "https://i.ibb.co/RTMq4Zdd/blackedraw-riley-reid-1900x1300.webp",
    "bio": "Riley Reid is a global superstar known for boundless energy and iconic status.",
  },
  "Rissa May": {
    "image": "https://i.ibb.co/0y9WHppt/Rissa-May-4.png",
    "card": "https://i.ibb.co/0y9WHppt/Rissa-May-4.png",
    "hero": "https://i.ibb.co/YBxn4VNv/slayed-rissa-may-3840x1600.webp",
    "portrait": "https://i.ibb.co/hxNvdrh4/slayed-rissa-may-1900x1300.webp",
    "bio": "Rissa May captivates with fresh, natural beauty.",
  },
  "Ryan Reid": {
    "image": "https://i.ibb.co/BJbJWbN/Ryan-Reid.png",
    "card": "https://i.ibb.co/BJbJWbN/Ryan-Reid.png",
    "hero": "https://i.ibb.co/PvjcF4QY/deeper-ryan-reid-3840x1600.webp",
    "portrait": "https://i.ibb.co/fdDX3xbb/deeper-ryan-reid-1900x1300.webp",
    "bio": "Ryan Reid delivers bold, confident performances.",
  },
  "Scarlett Alexis": {
    "image": "https://i.ibb.co/ynSyCbpw/Scarlett-Alexis-4.png",
    "card": "https://i.ibb.co/ynSyCbpw/Scarlett-Alexis-4.png",
    "hero": "https://i.ibb.co/fVxQWZSW/deeper-scarlett-alexis-3840x1600.webp",
    "portrait": "https://i.ibb.co/GyjXwms/deeper-scarlett-alexis-1900x1300.webp",
    "bio": "Scarlett Alexis blends classic beauty with modern edge.",
  },
  "Scarlett Jones": {
    "image": "https://i.ibb.co/7dLKLk7s/Scarlett-Jones-3.png",
    "card": "https://i.ibb.co/7dLKLk7s/Scarlett-Jones-3.png",
    "hero": "https://i.ibb.co/JR14vXLz/blacked-scarlett-jones-3840x1600.webp",
    "portrait": "https://i.ibb.co/gZp8HFjg/slayed-scarlett-jones-1900x1300.webp",
    "bio": "Scarlett Jones impresses with striking features and presence.",
  },
  "Scarlit Scandal": {
    "image": "https://i.ibb.co/qFpJHB0j/Scarlit-Scandal-4.png",
    "card": "https://i.ibb.co/qFpJHB0j/Scarlit-Scandal-4.png",
    "hero": "https://i.ibb.co/ZRHvQ0bd/blacked-scarlit-scandal-3840x1600.webp",
    "portrait": "https://i.ibb.co/SpHVTTP/vixen-scarlit-scandal-1900x1300.webp",
    "bio": "Scarlit Scandal creates headlines with bold beauty and talent.",
  },
  "Shay Sights": {
    "image": "https://i.ibb.co/FLgkM7Zq/Shay-Sights.png",
    "card": "https://i.ibb.co/FLgkM7Zq/Shay-Sights.png",
    "hero": "https://i.ibb.co/V0b29Smw/milfy-shay-sights-3840x1600.webp",
    "portrait": "https://i.ibb.co/PsGn084j/milfy-shay-sights-1900x1300.webp",
    "bio": "Shay Sights offers mature, sophisticated appeal.",
  },
  "Shelena": {
    "image": "https://i.ibb.co/pvmbWtgZ/Shelena.png",
    "card": "https://i.ibb.co/pvmbWtgZ/Shelena.png",
    "hero": "https://i.ibb.co/KpYSFH4w/vixen-shelena-3840x1600.webp",
    "portrait": "https://i.ibb.co/sJjbsp5K/vixen-shelena-1900x1300.webp",
    "bio": "Shelena captivates with unique, exotic beauty.",
  },
  "Sirena Milano": {
    "image": "https://i.ibb.co/0jsZrwhn/Sirena-Milano.png",
    "card": "https://i.ibb.co/0jsZrwhn/Sirena-Milano.png",
    "hero": "https://i.ibb.co/HLy3ZG84/vixen-sirena-milano-3840x1600.webp",
    "portrait": "https://i.ibb.co/svPdZMv2/tushyraw-sirena-milano-1900x1300.webp",
    "bio": "Sirena Milano sings with seductive Italian charm.",
  },
  "Sonya Blaze": {
    "image": "https://i.ibb.co/wZwCRwpP/Sonya-Blaze-2.png",
    "card": "https://i.ibb.co/wZwCRwpP/Sonya-Blaze-2.png",
    "hero": "https://i.ibb.co/xqyzYDTf/blackedraw-sonya-blaze-3840x1600.webp",
    "portrait": "https://i.ibb.co/xS3WCPTw/slayed-sonya-blaze-1900x1300.webp",
    "bio": "Sonya Blaze sets the screen on fire with passionate intensity.",
  },
  "Stefany Kyler": {
    "image": "https://i.ibb.co/N6jjqRfR/Stefany-Kyler-4.png",
    "card": "https://i.ibb.co/N6jjqRfR/Stefany-Kyler-4.png",
    "hero": "https://i.ibb.co/YB9FVQtn/tushy-stefany-kyler-3840x1600.webp",
    "portrait": "https://i.ibb.co/r2Xj0h4b/vixen-stefany-kyler-1900x1300.webp",
    "bio": "Stefany Kyler offers sweet, youthful European beauty.",
  },
  "Stella Luxx": {
    "image": "https://i.ibb.co/PvD47cYr/Stella-Luxx.png",
    "card": "https://i.ibb.co/PvD47cYr/Stella-Luxx.png",
    "hero": "https://i.ibb.co/zWZwTD1v/blackedraw-stella-luxx-3840x1600.webp",
    "portrait": "https://i.ibb.co/qF4Yk4r1/blackedraw-stella-luxx-1900x1300.webp",
    "bio": "Stella Luxx glows with luxurious appeal and star quality.",
  },
  "Sybil": {
    "image": "https://i.ibb.co/21LgvqxH/sybil-3.png",
    "card": "https://i.ibb.co/21LgvqxH/sybil-3.png",
    "hero": "https://i.ibb.co/Wp7xtZ0C/tushy-sybil-3840x1600.webp",
    "portrait": "https://i.ibb.co/dwCZ6nst/vixen-up-and-coming-3840x2160.webp",
    "bio": "Sybil enchants with elegant Eastern European sophistication.",
  },
  "Tori Black": {
    "image": "https://i.ibb.co/qMFM6Q1z/Tori-Black.png",
    "card": "https://i.ibb.co/qMFM6Q1z/Tori-Black.png",
    "hero": "https://i.ibb.co/rGmGGVkW/tushy-tori-black-3840x1600.webp",
    "portrait": "https://i.ibb.co/k6hs4DPr/tushy-tori-black-1900x1300.webp",
    "bio": "Tori Black is a legendary performer with timeless beauty and unmatched skill.",
  },
  "Valentina Nappi": {
    "image": "https://i.ibb.co/MD72mvkz/Valentina-Nappi.png",
    "card": "https://i.ibb.co/MD72mvkz/Valentina-Nappi.png",
    "hero": "https://i.ibb.co/shfWjsY/slayed-valentina-nappi-3840x1600.webp",
    "portrait": "https://i.ibb.co/n8mGTCTh/slayed-valentina-nappi-1900x1300.webp",
    "bio": "Valentina Nappi represents Italian perfection with incredible natural beauty.",
  },
  "Vanessa Alessia": {
    "image": "https://i.ibb.co/ZRV6g1N2/Vanessa-Alessia-2.png",
    "card": "https://i.ibb.co/ZRV6g1N2/Vanessa-Alessia-2.png",
    "hero": "https://i.ibb.co/275jnSBc/blacked-vanessa-alessia-3840x1600.webp",
    "portrait": "https://i.ibb.co/rGvgm0bx/vixen-vanessa-alessia-950x650.webp",
    "bio": "Vanessa Alessia brings warm, inviting sensuality.",
  },
  "Vanna Bardot": {
    "image": "https://i.ibb.co/RkwXPNfs/Vanna-Bardot.png",
    "card": "https://i.ibb.co/RkwXPNfs/Vanna-Bardot.png",
    "hero": "https://i.ibb.co/3ykLPR1P/tushy-vanna-bardot-3840x1600.webp",
    "portrait": "https://i.ibb.co/s9x3Pz3M/deeper-vanna-bardot-1900x1300.webp",
    "bio": "Vanna Bardot dazzles with delicate features and artistic performances.",
  },
  "Venus Valencia": {
    "image": "https://i.ibb.co/B23cHMcC/Venus-Valencia.png",
    "card": "https://i.ibb.co/B23cHMcC/Venus-Valencia.png",
    "hero": "https://i.ibb.co/FbTH7VPB/milfy-venus-valencia-3840x1600.webp",
    "portrait": "https://i.ibb.co/qFDX884Q/milfy-venus-valencia-1900x1300.webp",
    "bio": "Venus Valencia radiates divine beauty and passion.",
  },
  "Violet Gems": {
    "image": "https://i.ibb.co/placeholder/violet-gems.jpg",
    "card": "https://i.ibb.co/placeholder/violet-gems.jpg",
    "hero": "https://i.ibb.co/placeholder/violet-gems-hero.webp",
    "portrait": "https://i.ibb.co/placeholder/violet-gems-portrait.webp",
    "bio": "Violet Gems sparkles with precious, rare beauty.",
  },
  "Violet Myers": {
    "image": "https://i.ibb.co/SDvdwBqR/Violet-Myers-3.png",
    "card": "https://i.ibb.co/SDvdwBqR/Violet-Myers-3.png",
    "hero": "https://i.ibb.co/HL1vTwjn/blackedraw-violet-myers-3840x1600.webp",
    "portrait": "https://i.ibb.co/ymc5mZQS/slayed-violet-myers-1900x1300.webp",
    "bio": "Violet Myers is celebrated for her incredible curves and magnetic personality.",
  },
  "XxLayna Marie": {
    "image": "https://i.ibb.co/xqRntvZy/Xx-Layna-Marie-3.png",
    "card": "https://i.ibb.co/xqRntvZy/Xx-Layna-Marie-3.png",
    "hero": "https://i.ibb.co/354zJVHN/slayed-xxlayna-marie-3840x1600.webp",
    "portrait": "https://i.ibb.co/5XqtPvGr/deeper-xxlayna-marie-1900x1300.webp",
    "bio": "XxLayna Marie offers petite perfection and explosive energy.",
  },
  "Yhivi": {
    "image": "https://i.ibb.co/RTM5Sd3f/Yhivi.png",
    "card": "https://i.ibb.co/RTM5Sd3f/Yhivi.png",
    "hero": "https://i.ibb.co/nsYtLvt2/deeper-yhivi-3840x1600.webp",
    "portrait": "https://i.ibb.co/fz5x1vLg/deeper-yhivi-1900x1300.webp",
    "bio": "Yhivi stands out with unique style and artistic expression.",
  },
};

export function getModelProfile(name: string): ModelProfile {
  const fallback = `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent(name)}&backgroundColor=111111&textColor=ffffff`;
  const base = modelProfiles[name] ?? {
    image: fallback,
    bio: `${name} is a featured model on ExclusiveClips4, known for a refined presence in premium fashion and lifestyle features. Expect a distinctive style and consistently editorial-grade content.`,
  };
  return {
    ...base,
    card: base.card ?? base.image,
    hero: base.hero ?? base.image,
    portrait: base.portrait ?? base.image,
  };
}

export function slugifyModel(name: string): string {
  return name.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
}

export function unslugifyModel(slug: string): string | null {
  const target = slug.toLowerCase();
  return modelCodes.find((m) => slugifyModel(m) === target) ?? null;
}

export function getVideoEmbedUrl(src: string): string {
  if (src.startsWith("http://") || src.startsWith("https://")) return src;
  if (src.startsWith("//")) return `https:${src}`;
  return `https://${src.replace(/^\/+/, "")}`;
}

export function getVideoThumbnailUrl(thumb: string): string {
  if (thumb.startsWith("//")) return `https:${thumb}`;
  return thumb;
}

export function formatDuration(seconds: string): string {
  const s = parseInt(seconds, 10);
  const m = Math.floor(s / 60);
  const rem = s % 60;
  return `${m}:${rem.toString().padStart(2, "0")}`;
}

// Returns the list of models for a video. Supports comma/&/+ separated names
// in the `model` field (e.g. "Eliza Ibarra & Mick Blue").
export function getVideoModels(v: { model: string }): string[] {
  return v.model
    .split(/\s*(?:,|&|\+|\/| and )\s*/i)
    .map((m) => m.trim())
    .filter(Boolean);
}

export function videoHasModel(v: { model: string }, name: string): boolean {
  return getVideoModels(v).some((m) => m.toLowerCase() === name.toLowerCase());
}
